enable-magisk-update = false # set this to false if you do not want to receive updates for the module in magisk app
parallel-jobs = 1

# add 'enabled = false' for not patching a specific app or remove it from the config
# see https://github.com/j-hc/revanced-magisk-module/blob/main/CONFIG.md for more detailed explanations

# you can use rvmm-config-gen to generate a config

[YouTube-Morphe]
build-mode = "apk"
exclusive-patches = true
included-patches = "'Hide ads' 'Remove background playback restrictions' 'Navigation bar' 'Video ads' 'Sanitize sharing links' 'SponsorBlock' 'Bypass URL redirects' 'Open links externally' 'Spoof video streams'"
excluded-patches = ""
version = "latest"
patches-version = "dev"
uptodown-dlurl = "https://youtube.en.uptodown.com/android"
patches-source = "MorpheApp/morphe-patches"
cli-source = "MorpheApp/morphe-cli"
